services:

   localstack: # LocalStack container
       image: localstack/localstack:latest
       ports:
         # Map the port, so you can access the API from the host machine
         - 4566:4566 # LocalStack main endpoint
         - 8000:8000 # DynamoDB local UI
       environment:
         - AWS_ACCESS_KEY_ID=test
         - AWS_SECRET_ACCESS_KEY=test
         - AWS_REGION=us-east-1
         - AWS_DEFAULT_REGION=us-east-1
         - SERVICES=sns,sqs,dynamodb
         - DEBUG=1
         - PERSISTENCE=1
       volumes:
         - ./localstack-data:/var/lib/localstack
         - ./localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh