package com.christmas.letter.processor.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import lombok.Data;


@Data
@DynamoDBTable(tableName = "SantaChristmasLetters")
public class Letter {

  @DynamoDBHashKey(attributeName = "email")
  @DynamoDBAutoGeneratedKey
  private String email;
  @DynamoDBAttribute(attributeName = "name")
  private String name;
  @DynamoDBAttribute(attributeName = "wishes")
  private String wishes;
  @DynamoDBTypeConvertedJson
  @DynamoDBAttribute(attributeName = "location")
  private Location location;

}
